apiVersion: v1
kind: Service
metadata:
  name: qwenpaw-hub
  labels:
    app.kubernetes.io/name: qwenpaw-hub
spec:
  type: {{ .Values.hub.service.type }}
  selector:
    app.kubernetes.io/name: qwenpaw-hub
  ports:
    - name: http
      port: {{ .Values.hub.service.port }}
      targetPort: http
